project:
  type: website
  output-dir: docs

website:
  title: "Advent of SQL"
  favicon: favicon.ico
  search: false
  
  navbar:
    pinned: true
    left:
      - 2024.qmd
      - 2025.qmd
      - about.qmd

highlight-style: a11y-dark

format:
  html:
    page-layout: full
    grid:
      body-width: 500px
    theme:
      - none
      - sass/main.scss
    number-sections: false
    toc: false