name: Lint SQL queries

on:
  push:

jobs:
  lint-queries:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›Ž Check out repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv venv .venv --python 3.12
          uv python install 3.13
          source .venv/bin/activate
          uv pip install -r requirements.txt

      - name: Lint SQL files
        run: |
          source .venv/bin/activate
          sqlfluff lint .
